version: '3'

services:
  app:
    build: ./
    image: mean
    expose:
      - 5050
      - 4040
    environment:
      NODE_ENV: production
      SERVER_PORT: 4040
      WEBSOCKET_PORT: 5050
      JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      MONGO_URL: mongodb://mongo/odmp
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
